apiVersion: apps/v1

kind: Deployment

metadata:
  name: service1-deployment
  labels:
    app: service1

spec:
  replicas: 2
  
  selector:
    matchLabels:
      app: service1

  template:
    metadata:
      labels:
        app: service1
        
    spec:
      containers:
        - name: vjezba-service1
          image: vjezba-servis1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9000

---
apiVersion: v1

kind: Service

metadata:
  name: service1-srv

spec:
  selector:
    app: service1

  ports:
    - port: 3210
      targetPort: 9000